### ISSUE TITLE
Nothing is loading

### ISSUE THREAD

**Issue by YourMajestyTheEye** [Abyss-Services/abyss-browser-OLD#13]
![image](https://user-images.githubusercontent.com/115742960/213484516-6c981dce-98f2-4607-9ce0-0f3da1d8874f.png)

**Comment by YourMajestyTheEye** [comment]
ohhh but why does it still say that there are 260 commits?

**Comment by notAperson535** [comment]
We are rewriting abyss, so this repo is now archived
